# Generated by Django 6.0.6 on 2026-06-26 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_project_sample_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(blank=True, db_index=True, max_length=16)),
                ('severity_number', models.PositiveSmallIntegerField(default=0)),
                ('body', models.TextField(blank=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('span_id', models.CharField(blank=True, max_length=16)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, max_length=128)),
                ('attributes', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='organizations.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', '-timestamp'], name='logs_logent_project_711f62_idx'), models.Index(fields=['project', 'level', '-timestamp'], name='logs_logent_project_a30741_idx'), models.Index(fields=['project', 'trace_id'], name='logs_logent_project_0276a2_idx')],
            },
        ),
    ]
