"""
Auto-fix orchestration (Seer-style). Resolves the AI config, builds context,
asks the provider for a patch, opens a GitLab merge request, and records the
run — emitting signals at each milestone for notifications.
"""

from __future__ import annotations

import difflib
import logging

from django.utils import timezone

from .context import build_context
from .models import AIConfig, AutoFixRun
from .providers import get_provider
from .signals import autofix_failed, autofix_mr_created, autofix_started

logger = logging.getLogger(__name__)


def resolve_config(project) -> AIConfig | None:
    """Project-scoped config wins over org-scoped."""
    cfg = AIConfig.objects.filter(project=project, enabled=True).first()
    if cfg:
        return cfg
    return AIConfig.objects.filter(
        organization=project.organization, project__isnull=True, enabled=True
    ).first()


def _set(run: AutoFixRun, **fields) -> None:
    for k, v in fields.items():
        setattr(run, k, v)
    run.save(update_fields=[*fields.keys(), "updated_at"])


def run_autofix(run: AutoFixRun) -> AutoFixRun:
    issue = run.issue
    project = issue.project
    config = resolve_config(project)

    autofix_started.send(sender=AutoFixRun, run=run)
    issue.autofix_state = "running"
    issue.save(update_fields=["autofix_state"])

    try:
        if config is None:
            raise RuntimeError("No AI configuration for this project/organization.")
        if project.repository is None:
            raise RuntimeError("Project has no linked repository to open a merge request.")

        _set(run, status=AutoFixRun.Status.ANALYZING, provider=config.provider, model=config.model)
        context = build_context(issue)

        _set(run, status=AutoFixRun.Status.GENERATING)
        result = get_provider(config).generate_fix(context)
        if not result.changes:
            raise RuntimeError("Model returned no file changes.")

        _set(
            run,
            status=AutoFixRun.Status.CREATING_MR,
            explanation=result.explanation,
            tokens_used=result.tokens_used,
            diff=_render_diff(result.changes, context.source_files),
        )

        from apps.integrations.clients import get_client

        repo = project.repository
        client = get_client(repo.integration)
        branch = f"errora/autofix-{str(issue.id)[:8]}-{int(timezone.now().timestamp())}"
        mr = client.create_merge_request(
            repo.external_id,
            source_branch=branch,
            target_branch=repo.default_branch,
            title=f"fix: {issue.title[:80]}",
            description=_mr_description(issue, result.explanation),
            changes={p.lstrip("/"): c for p, c in result.changes.items()},
        )

        _set(run, status=AutoFixRun.Status.COMPLETED, mr_url=mr.url, branch=branch)
        issue.autofix_state = "mr_created"
        issue.save(update_fields=["autofix_state"])
        autofix_mr_created.send(sender=AutoFixRun, run=run)
    except Exception as exc:  # noqa: BLE001 - record and notify, never crash the worker
        logger.exception("autofix run %s failed", run.id)
        _set(run, status=AutoFixRun.Status.FAILED, error=str(exc))
        issue.autofix_state = "failed"
        issue.save(update_fields=["autofix_state"])
        autofix_failed.send(sender=AutoFixRun, run=run)
    return run


def _render_diff(changes: dict[str, str], originals: dict[str, str] | None = None) -> str:
    """Real unified diff of each changed file against its original content
    (empty when the file is newly created or wasn't fetched into context)."""
    originals = originals or {}
    out: list[str] = []
    for path, new_content in changes.items():
        old = originals.get(path) or originals.get(path.lstrip("/")) or ""
        old_lines = old.splitlines(keepends=True)
        new_lines = new_content.splitlines(keepends=True)
        label = "new file" if not old else path
        diff = difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"a/{path}" if old else "/dev/null",
            tofile=f"b/{path}",
            lineterm="",
        )
        body = "".join(line if line.endswith("\n") else f"{line}\n" for line in diff)
        out.append(f"# {label}\n{body}".rstrip())
    return "\n\n".join(out)


def _mr_description(issue, explanation: str) -> str:
    return (
        f"## 🤖 Errora auto-fix\n\n"
        f"Proposed fix for issue **{issue.title}**.\n\n"
        f"### Explanation\n{explanation}\n\n"
        f"---\n_Generated by Errora. Review carefully before merging._"
    )
