# Generated by Django 6.0.6 on 2026-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
