# Generated by Django 6.0.6 on 2026-06-28 12:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSpan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('transaction_event_id', models.UUIDField(blank=True, null=True)),
                ('span_id', models.CharField(blank=True, max_length=16)),
                ('parent_span_id', models.CharField(blank=True, max_length=16)),
                ('op', models.CharField(blank=True, max_length=64)),
                ('kind', models.CharField(choices=[('agent', 'Agent run'), ('llm', 'LLM call'), ('tool', 'Tool call'), ('handoff', 'Handoff'), ('embeddings', 'Embeddings'), ('mcp', 'MCP request')], db_index=True, max_length=16)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, db_index=True, max_length=128)),
                ('agent_name', models.CharField(blank=True, max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('reasoning_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('tool_name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('mcp_method', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mcp_tool', models.CharField(blank=True, max_length=128)),
                ('mcp_resource', models.CharField(blank=True, max_length=256)),
                ('mcp_prompt', models.CharField(blank=True, max_length=128)),
                ('mcp_transport', models.CharField(blank=True, max_length=32)),
                ('client_address', models.CharField(blank=True, db_index=True, max_length=128)),
                ('client_name', models.CharField(blank=True, max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_spans', to='organizations.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'kind', '-timestamp'], name='insights_ai_project_fbb45a_idx'), models.Index(fields=['project', '-timestamp'], name='insights_ai_project_1d0ecf_idx'), models.Index(fields=['project', 'model'], name='insights_ai_project_e75d83_idx'), models.Index(fields=['project', 'tool_name'], name='insights_ai_project_cb7976_idx'), models.Index(fields=['project', 'client_address'], name='insights_ai_project_fef18b_idx'), models.Index(fields=['trace_id'], name='insights_ai_trace_i_f5047c_idx')],
            },
        ),
    ]
