# Generated by Django 6.0.6 on 2026-06-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aispan',
            name='insights_ai_project_e75d83_idx',
        ),
        migrations.RemoveIndex(
            model_name='aispan',
            name='insights_ai_project_cb7976_idx',
        ),
        migrations.RemoveIndex(
            model_name='aispan',
            name='insights_ai_project_fef18b_idx',
        ),
    ]
