# Generated by Django 5.2.15 on 2026-06-19 18:43

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI-compatible"),
                            ("claude", "Claude Agent SDK"),
                            ("cursor", "Cursor Agents SDK"),
                        ],
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("api_key", apps.common.fields.EncryptedTextField(blank=True)),
                ("model", models.CharField(default="claude-opus-4-8", max_length=120)),
                (
                    "auto_trigger",
                    models.BooleanField(
                        default=False, help_text="Automatically open a fix MR on new unique issues."
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AutoFixRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("model", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("analyzing", "Analyzing"),
                            ("generating", "Generating fix"),
                            ("creating_mr", "Creating merge request"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("diff", models.TextField(blank=True)),
                ("mr_url", models.URLField(blank=True)),
                ("branch", models.CharField(blank=True, max_length=200)),
                ("error", models.TextField(blank=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
