# Generated by Django 5.2.15 on 2026-06-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("issues", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconfig",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_configs",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="aiconfig",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_configs",
                to="organizations.project",
            ),
        ),
        migrations.AddField(
            model_name="autofixrun",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autofix_runs",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="autofixrun",
            name="triggered_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiconfig",
            unique_together={("organization", "project")},
        ),
    ]
