# Generated by Django 6.0.6 on 2026-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconfig',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='aiconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='name',
            field=models.CharField(blank=True, help_text='Label for this agent.', max_length=120),
        ),
    ]
