# Generated by Django 5.2.15 on 2026-06-19 18:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("name_fa", models.CharField(blank=True, max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("price_toman_monthly", models.BigIntegerField(default=0)),
                ("price_toman_yearly", models.BigIntegerField(default=0)),
                ("included_events", models.BigIntegerField(default=0)),
                (
                    "payg_per_event_toman",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("max_seats", models.PositiveIntegerField(default=1)),
                ("is_payg", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("features", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("payg_enabled", models.BooleanField(default=False)),
                ("current_period_start", models.DateField(default=django.utils.timezone.localdate)),
                ("current_period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("period", models.CharField(db_index=True, max_length=7)),
                ("events_count", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
