# Generated by Django 5.2.15 on 2026-06-19 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("primary_hash", models.CharField(max_length=64)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                ("culprit", models.CharField(blank=True, max_length=512)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("fatal", "Fatal"),
                        ],
                        default="error",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="unresolved",
                        max_length=12,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("times_seen", models.PositiveIntegerField(default=0)),
                ("users_seen", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("autofix_state", models.CharField(blank=True, default="", max_length=20)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="organizations.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "event_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("fatal", "Fatal"),
                        ],
                        default="error",
                        max_length=10,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=32)),
                ("environment", models.CharField(blank=True, db_index=True, max_length=64)),
                ("release", models.CharField(blank=True, max_length=128)),
                ("server_name", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="organizations.project",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="issues.issue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssueHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hash", models.CharField(max_length=64)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hashes",
                        to="issues.issue",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organizations.project"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "status", "-last_seen"], name="issues_issu_project_e08196_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["project", "-times_seen"], name="issues_issu_project_95fe7b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("project", "primary_hash")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["issue", "-timestamp"], name="issues_even_issue_i_120114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["project", "-timestamp"], name="issues_even_project_691336_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issuehash",
            unique_together={("project", "hash")},
        ),
    ]
