# Generated by Django 6.0.6 on 2026-06-19 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="assignee",
        ),
        migrations.AddField(
            model_name="issue",
            name="assignees",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_issues", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
