# Generated by Django 6.0.6 on 2026-06-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_assignee_issue_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
