# Generated by Django 6.0.6 on 2026-06-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
