# Generated by Django 6.0.6 on 2026-06-26 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_initial'),
        ('issues', '0009_issue_sqlite_fts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('archived', 'Archived')], default='unresolved', max_length=12),
        ),
        migrations.CreateModel(
            name='IssueExternalIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('web_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_issues', to='issues.issue')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_issues', to='integrations.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('issue', 'repository', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='IssueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=64)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_users', to='issues.issue')),
            ],
            options={
                'unique_together': {('issue', 'ident')},
            },
        ),
    ]
