# Generated by Django 6.0.6 on 2026-06-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_token_version'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_phone_f54457_idx',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(choices=[('email', 'Email')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
    ]
