# Generated by Django 5.2.15 on 2026-06-19 18:43

import apps.common.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("gitlab", "GitLab (self-hosted or SaaS)"), ("github", "GitHub")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=120)),
                ("base_url", models.URLField(default="https://gitlab.com")),
                ("access_token", apps.common.fields.EncryptedTextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("path_with_namespace", models.CharField(max_length=512)),
                ("web_url", models.URLField(blank=True)),
                ("default_branch", models.CharField(default="main", max_length=120)),
            ],
            options={
                "verbose_name_plural": "repositories",
            },
        ),
    ]
