# Generated by Django 5.2.15 on 2026-06-19 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="integrations.integration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("integration", "external_id")},
        ),
    ]
