# Generated by Django 6.0.6 on 2026-06-26 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_organization_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('release', models.CharField(db_index=True, max_length=250)),
                ('dist', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=1024)),
                ('headers', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_artifacts', to='organizations.project')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['project', 'release', 'dist'], name='sourcemaps__project_e04274_idx')],
                'unique_together': {('project', 'release', 'dist', 'name')},
            },
        ),
    ]
