# Generated by Django 6.0.6 on 2026-06-25 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_project_sample_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('op', models.CharField(blank=True, max_length=64)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_groups', to='organizations.project')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('span_id', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=512)),
                ('op', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('environment', models.CharField(blank=True, db_index=True, max_length=64)),
                ('release', models.CharField(blank=True, max_length=128)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('spans', models.JSONField(default=list)),
                ('data', models.JSONField(default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.project')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='performance.transactiongroup')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transactiongroup',
            index=models.Index(fields=['project', '-last_seen'], name='performance_project_f5438f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiongroup',
            index=models.Index(fields=['project', '-times_seen'], name='performance_project_b2ba30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiongroup',
            unique_together={('project', 'fingerprint')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['group', '-timestamp'], name='performance_group_i_f92bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', '-timestamp'], name='performance_project_1652df_idx'),
        ),
    ]
