# Generated by Django 6.0.6 on 2026-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
