# Generated by Django 6.0.6 on 2026-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_project_sample_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
